'use strict';

const express = require('express');
const router = express.Router();
const prisma = require('../db/prisma');
const { requireAuth } = require('../middleware/auth');
const { createLeadGenerationPlan, createExecutableSequenceSteps } = require('../services/eventLeadAgent');

function computeNextSendAt(delayDays) {
  const d = new Date();
  d.setDate(d.getDate() + Number(delayDays || 0));
  d.setHours(9, 0, 0, 0);
  return d;
}

function resolveEventName(payload = {}) {
  return typeof payload.eventName === 'string' && payload.eventName.trim()
    ? payload.eventName
    : payload.prompt;
}

function buildPlanFromPayload(payload = {}) {
  return createLeadGenerationPlan({
    eventName: resolveEventName(payload),
    targetPersona: payload.targetPersona,
    offer: payload.offer,
    idealCustomerProfile: payload.idealCustomerProfile,
    coverageGoal: payload.coverageGoal,
    brandName: 'Logical Data Solution',
    brandWebsite: 'logicaldatasolution.com',
  });
}

async function resolveEvent(tx, payload, plan) {
  if (payload.reuseEventId) {
    const existing = await tx.event.findUnique({ where: { id: String(payload.reuseEventId) } });
    if (!existing) throw new Error('reuseEventId not found');
    return existing;
  }

  return tx.event.create({
    data: {
      name: plan.event.name,
      website: payload.eventWebsite || null,
      location: payload.eventLocation || null,
      startDate: payload.startDate ? new Date(payload.startDate) : null,
      endDate: payload.endDate ? new Date(payload.endDate) : null,
      notes: payload.eventNotes || `Generated by Event Agent for ${plan.event.name}`,
    },
  });
}

async function resolveSequence(tx, reqUserId, payload, plan, executableSteps) {
  if (payload.reuseSequenceId) {
    const existing = await tx.sequence.findFirst({
      where: { id: String(payload.reuseSequenceId), userId: reqUserId },
      include: { steps: { orderBy: { stepNumber: 'asc' } } },
    });
    if (!existing) throw new Error('reuseSequenceId not found for current user');
    if (!existing.steps.length) throw new Error('reuseSequenceId has no steps');
    return existing;
  }

  return tx.sequence.create({
    data: {
      userId: reqUserId,
      name: payload.sequenceName || `${plan.event.name} Revenue Cadence`,
      description: payload.sequenceDescription || `Auto-generated plan for ${plan.event.name}`,
      steps: {
        create: executableSteps.map((step, index) => ({
          stepNumber: index + 1,
          subject: step.subject,
          body: step.body,
          delayDays: step.delayDays,
        })),
      },
    },
    include: { steps: { orderBy: { stepNumber: 'asc' } } },
  });
}

async function resolveCandidateContacts(tx, payload) {
  if (Array.isArray(payload.contactIds) && payload.contactIds.length) {
    const uniqueIds = [...new Set(payload.contactIds.map((id) => String(id)))];
    const contacts = await tx.contact.findMany({ where: { id: { in: uniqueIds } }, select: { id: true } });
    if (contacts.length !== uniqueIds.length) throw new Error('Some contactIds were not found');
    return uniqueIds;
  }

  const contactWhere = {
    doNotContact: false,
    unsubscribed: false,
  };
  if (payload.sourceEventId) contactWhere.eventId = String(payload.sourceEventId);

  const found = await tx.contact.findMany({
    where: contactWhere,
    select: { id: true },
    take: Number(payload.maxContacts || 500),
  });
  return found.map((c) => c.id);
}

router.post('/event-plan', requireAuth, async (req, res) => {
  const resolvedEventName = resolveEventName(req.body || {});

  if (!resolvedEventName || typeof resolvedEventName !== 'string' || !resolvedEventName.trim()) {
    return res.status(400).json({ ok: false, error: 'eventName (or prompt) is required' });
  }

  const plan = buildPlanFromPayload(req.body || {});
  return res.json(plan);
});

router.post('/event-plan/execute', requireAuth, async (req, res) => {
  const payload = req.body || {};
  const resolvedEventName = resolveEventName(payload);

  if (!resolvedEventName || typeof resolvedEventName !== 'string' || !resolvedEventName.trim()) {
    return res.status(400).json({ ok: false, error: 'eventName (or prompt) is required' });
  }

  const plan = buildPlanFromPayload(payload);
  const executableSteps = createExecutableSequenceSteps(plan);
  if (!executableSteps.length) {
    return res.status(400).json({ ok: false, error: 'No executable email steps found in generated plan' });
  }

  try {
    const execution = await prisma.$transaction(async (tx) => {
      const event = await resolveEvent(tx, payload, plan);
      const sequence = await resolveSequence(tx, req.user.id, payload, plan, executableSteps);
      const candidateIds = await resolveCandidateContacts(tx, payload);

      const firstStepDelay = sequence.steps[0]?.delayDays || 0;
      const nextSendAt = computeNextSendAt(firstStepDelay);

      let enrolled = 0;
      let skipped = 0;
      const skippedReasons = { not_found_or_dnc: 0, suppressed: 0 };

      for (const contactId of candidateIds) {
        const contact = await tx.contact.findUnique({ where: { id: contactId } });
        if (!contact || contact.doNotContact || contact.unsubscribed) {
          skipped++;
          skippedReasons.not_found_or_dnc++;
          continue;
        }

        const suppressed = await tx.suppression.findUnique({ where: { email: contact.email } });
        if (suppressed) {
          skipped++;
          skippedReasons.suppressed++;
          continue;
        }

        await tx.enrollment.upsert({
          where: { contactId_sequenceId: { contactId, sequenceId: sequence.id } },
          create: {
            contactId,
            sequenceId: sequence.id,
            userId: req.user.id,
            eventId: event.id,
            status: 'active',
            currentStep: 0,
            nextSendAt,
          },
          update: {
            status: 'active',
            currentStep: 0,
            nextSendAt,
            eventId: event.id,
          },
        });
        enrolled++;
      }

      await tx.activityLog.create({
        data: {
          userId: req.user.id,
          type: 'agent_execution',
          metadata: {
            eventId: event.id,
            sequenceId: sequence.id,
            enrolled,
            skipped,
            skippedReasons,
            usedProvidedContactIds: Boolean(payload.contactIds?.length),
          },
        },
      });

      return {
        eventId: event.id,
        sequenceId: sequence.id,
        sequenceStepCount: sequence.steps.length,
        enrolled,
        skipped,
        skippedReasons,
      };
    });

    return res.status(201).json({ ok: true, execution, plan });
  } catch (err) {
    const message = err?.message || 'Failed to execute event plan';
    const status = /not found|no steps|contactIds/i.test(message) ? 400 : 500;
    return res.status(status).json({ ok: false, error: message });
  }
});

module.exports = router;
