'use strict';

const express = require('express');
const router = express.Router();
const prisma = require('../db/prisma');
const { requireAuth } = require('../middleware/auth');
const { createLeadGenerationPlan, createExecutableSequenceSteps } = require('../services/eventLeadAgent');

function computeNextSendAt(delayDays) {
  const d = new Date();
  d.setDate(d.getDate() + Number(delayDays || 0));
  d.setHours(9, 0, 0, 0);
  return d;
}

function resolveEventName(payload = {}) {
  return typeof payload.eventName === 'string' && payload.eventName.trim()
    ? payload.eventName
    : payload.prompt;
}

function buildPlanFromPayload(payload = {}) {
  return createLeadGenerationPlan({
    eventName: resolveEventName(payload),
    targetPersona: payload.targetPersona,
    offer: payload.offer,
    idealCustomerProfile: payload.idealCustomerProfile,
    coverageGoal: payload.coverageGoal,
    brandName: 'Logical Data Solution',
    brandWebsite: 'logicaldatasolution.com',
  });
}

router.post('/event-plan', requireAuth, async (req, res) => {
  const resolvedEventName = resolveEventName(req.body || {});

  if (!resolvedEventName || typeof resolvedEventName !== 'string' || !resolvedEventName.trim()) {
    return res.status(400).json({ ok: false, error: 'eventName (or prompt) is required' });
  }

  const plan = buildPlanFromPayload(req.body || {});
  return res.json(plan);
});

router.post('/event-plan/execute', requireAuth, async (req, res) => {
  const payload = req.body || {};
  const resolvedEventName = resolveEventName(payload);

  if (!resolvedEventName || typeof resolvedEventName !== 'string' || !resolvedEventName.trim()) {
    return res.status(400).json({ ok: false, error: 'eventName (or prompt) is required' });
  }

  const plan = buildPlanFromPayload(payload);
  const executableSteps = createExecutableSequenceSteps(plan);
  if (!executableSteps.length) {
    return res.status(400).json({ ok: false, error: 'No executable email steps found in generated plan' });
  }

  try {
    const event = await prisma.event.create({
      data: {
        name: plan.event.name,
        website: payload.eventWebsite || null,
        location: payload.eventLocation || null,
        startDate: payload.startDate ? new Date(payload.startDate) : null,
        endDate: payload.endDate ? new Date(payload.endDate) : null,
        notes: payload.eventNotes || `Generated by Event Agent for ${plan.event.name}`,
      },
    });

    const sequence = await prisma.sequence.create({
      data: {
        userId: req.user.id,
        name: payload.sequenceName || `${plan.event.name} Revenue Cadence`,
        description: payload.sequenceDescription || `Auto-generated plan for ${plan.event.name}`,
        steps: {
          create: executableSteps.map((step, index) => ({
            stepNumber: index + 1,
            subject: step.subject,
            body: step.body,
            delayDays: step.delayDays,
          })),
        },
      },
      include: { steps: { orderBy: { stepNumber: 'asc' } } },
    });

    const contactWhere = {
      doNotContact: false,
      unsubscribed: false,
    };
    if (payload.sourceEventId) contactWhere.eventId = String(payload.sourceEventId);

    const candidateIds = Array.isArray(payload.contactIds) && payload.contactIds.length
      ? payload.contactIds
      : (await prisma.contact.findMany({
        where: contactWhere,
        select: { id: true },
        take: Number(payload.maxContacts || 500),
      })).map((c) => c.id);

    const firstStepDelay = sequence.steps[0]?.delayDays || 0;
    const nextSendAt = computeNextSendAt(firstStepDelay);

    let enrolled = 0;
    let skipped = 0;
    for (const contactId of candidateIds) {
      const contact = await prisma.contact.findUnique({ where: { id: contactId } });
      if (!contact || contact.doNotContact || contact.unsubscribed) {
        skipped++;
        continue;
      }

      const suppressed = await prisma.suppression.findUnique({ where: { email: contact.email } });
      if (suppressed) {
        skipped++;
        continue;
      }

      await prisma.enrollment.upsert({
        where: { contactId_sequenceId: { contactId, sequenceId: sequence.id } },
        create: {
          contactId,
          sequenceId: sequence.id,
          userId: req.user.id,
          eventId: event.id,
          status: 'active',
          currentStep: 0,
          nextSendAt,
        },
        update: {
          status: 'active',
          currentStep: 0,
          nextSendAt,
          eventId: event.id,
        },
      });
      enrolled++;
    }

    return res.status(201).json({
      ok: true,
      execution: {
        eventId: event.id,
        sequenceId: sequence.id,
        sequenceStepCount: sequence.steps.length,
        enrolled,
        skipped,
      },
      plan,
    });
  } catch (err) {
    return res.status(500).json({ ok: false, error: err.message });
  }
});

module.exports = router;
